// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace RealtimeKanbanBoard.Models.Migrations
{
    public sealed partial class Initalschema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initalschema));
        
        string IMigrationMetadata.Id
        {
            get { return "201302021830028_initalschema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
